title: Designing and Architecting Intelligent Agents
description: Microsoft labs for learning to design and architect intelligent bots.
show_downloads: true
theme: jekyll-theme-cayman
repository: Azure/LearnAI-DesigningandArchitectingIntelligentAgents